# Generated by Django 3.2.2 on 2021-06-03 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_follower'),
        ('home', '0007_tweetcomment_like_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLike',
            fields=[
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notified', to='authentication.basicuserprofile')),
                ('notifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='authentication.basicuserprofile')),
                ('tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tweet')),
            ],
        ),
    ]
