# Generated by Django 3.2.2 on 2021-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuserprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
