# Generated by Django 3.2.2 on 2021-06-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_basicuserprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuserprofile',
            name='banner_photo',
            field=models.ImageField(blank=True, null=True, upload_to='banner_photo/'),
        ),
    ]
