# Generated by Django 3.2.2 on 2021-05-21 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_follower'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetRetweet',
            fields=[
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('retweeter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.basicuserprofile')),
                ('tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetLike',
            fields=[
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.basicuserprofile')),
                ('tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetComment',
            fields=[
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('commentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.basicuserprofile')),
                ('tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tweet')),
            ],
        ),
    ]
