# Generated by Django 3.2.2 on 2021-05-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('home', '0002_tweetcomment_tweetlike_tweetretweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hashtag.topic'),
        ),
    ]
