# Generated by Django 3.2.2 on 2021-06-03 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_follower'),
        ('home', '0003_tweet_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetCommentLike',
            fields=[
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.basicuserprofile')),
                ('tweet_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tweetcomment')),
            ],
        ),
    ]
