# Generated by Django 3.2.2 on 2021-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210603_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_like_amount',
            field=models.IntegerField(default=0),
        ),
    ]
